var console=window&&window.console?window.console:{log:function(){}},DEXTTOP=parent;DEXTTOP.DEXT5=parent.DEXT5;DEXTTOP.G_CURREDITOR=null;parent.DEXTTOP=DEXTTOP;DEXTTOP.DEXTDOC=parent.document;DEXTTOP.G_LIGHTVIEWDOC||(DEXTTOP.G_LIGHTVIEWDOC={});
function loadEditorFn(d,b,a){var f=document.getElementById("editorContentArea"),c;c=""+('<div id="ue_editor_main_'+d+'" class="DEXT_fiVe_EdiTor" style="z-index:99999; width:100%; "  oncontextmenu="return false">')+('\t<div id="ue_editor_holder_'+d+'" class="ue_editor_'+b.style.skinName+'_lr" ');if(DEXTTOP.DEXT5.browser.mobile||DEXTTOP.DEXT5.browser.iOS)c="1"==_this._config.view_mode_auto_height?c+' style="overflow:hidden;"':c+' style="overflow:scroll; -webkit-overflow-scrolling:touch;"';c+="\t></div>";
f.innerHTML=c;f=document.getElementById("ue_editor_holder_"+d);"0"==b.editorborder&&(f.style.borderWidth="0px");var e=document.createElement("iframe");e.id="dext5_lightview_"+d;e.title="dext5_lightview_"+d;e.frameBorder=0;e.style.width="100%";e.style.height="100%";e.style.borderWidth="0px";if(DEXTTOP.DEXT5.browser.mobile||DEXTTOP.DEXT5.browser.iOS)e.style.overflow="hidden",e.style.display="inline-block";c="document.open();"+(DEXTTOP.DEXT5.util.DEXT5_IsCustomDomain(document)?'document="'+document+
'";':"")+" document.close();";c=DEXTTOP.DEXT5.browser.ie&&12>DEXTTOP.DEXT5.browser.ieVersion?"javascript:void(function(){"+encodeURIComponent(c)+"}())":"";e.src=c;c=b.style.height;if(0<DEXTTOP.DEXT5.util.parseIntOr0(c))if(-1<c.toString().indexOf("%"))f.style.height=c;else{var g=2;7==DEXTTOP.DEXT5.browser.trident||12<=DEXTTOP.DEXT5.browser.ieVersion||!DEXTTOP.DEXT5.browser.quirks||(g=0);f.style.height=parseInt(c,10)-g+"px"}c={};c.Auto=DEXTTOP.DEXT5.util.getDocType(DEXTTOP.document);c.None="";c["XHTML 1.1"]=
'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">';c["XHTML 1.0 Transitional"]='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">';c["XHTML 1.0 Strict"]='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">';c["XHTML 1.0 Frameset"]='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">';
c["HTML 5"]="<!DOCTYPE html>";c["HTML 4.01 Transitional"]='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">';c["HTML 4.01 Strict"]='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">';c["HTML 4.01 Frameset"]='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">';c["HTML 3.2"]='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">';c["HTML 2.0"]='<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">';
DEXTTOP.G_CURREDITOR._docType=c;a._PageProp={};a._PageProp.doctype="HTML 5";""!=b.docType&&(a._PageProp.doctype=b.docType);e.onload=function(){e.onload=null;var b=e.contentDocument?e.contentDocument:e.contentWindow.document;b.body.spellcheck="false";b.body.contentEditable="false";b.body.style.cursor="auto";a._BODY=b.body;a._DOC=b;DEXTTOP.G_LIGHTVIEWDOC[d]=b;if(a._config.userCssUrl&&""!=a._config.userCssUrl){var c=b.createElement("link");c.type="text/css";c.rel="stylesheet";c.href=a._config.userCssUrl;
b.getElementsByTagName("head")[0].appendChild(c)}DEXTTOP.DEXT5.LIGHTVIEWEVT||(DEXTTOP.DEXT5.LIGHTVIEWEVT={});var c=function(a){var b="which"in a?a.which:a.keyCode;(a.ctrlKey||a.metaKey)&&"0"==DEXTTOP.G_CURREDITOR._config.viewModeAllowCopy&&67==b&&DEXTTOP.DEXT5.util.cancelEvent(a)},f=function(a){"1"==DEXTTOP.G_CURREDITOR._config.viewModeBrowserMenu&&DEXTTOP.DEXT5.util.cancelEvent(a)};DEXTTOP.DEXT5.LIGHTVIEWEVT._lightView_Keydown=c;DEXTTOP.DEXT5.LIGHTVIEWEVT._lightView_Contextmenu=f;DEXTTOP.DEXT5.util.addEventEx(b,
"keydown",c,!1);DEXTTOP.DEXT5.util.addEventEx(b,"contextmenu",f,!1);try{"function"==typeof a._config.event.loadedEvent?a._config.event.loadedEvent(a):"function"==typeof a._config.LoadedEvent?a._config.LoadedEvent(a):"function"==typeof DEXTTOP.dext_editor_loaded_event&&DEXTTOP.dext_editor_loaded_event(a)}catch(g){DEXTTOP&&DEXTTOP.DEXT5&&DEXTTOP.DEXT5.logMode&&console.log(g)}DEXTTOP.DEXT5.InitEditorDataHashTable&&(b=DEXTTOP.DEXT5.InitEditorDataHashTable.getItem(a.ID),"undefined"!=typeof b&&("object"==
typeof b?"setHtmlValueExWithDocType"==b.mode?DEXTTOP.DEXT5.setHtmlValueExWithDocType(b.value,a.ID):"setHtmlValueEx"==b.mode?DEXTTOP.DEXT5.setHtmlValueEx(b.value,a.ID):"setHtmlValue"==b.mode?DEXTTOP.DEXT5.setHtmlValue(b.value,a.ID):"setBodyValueEx"==b.mode?DEXTTOP.DEXT5.setBodyValueEx(b.value,a.ID):"setBodyValueExLikeDiv"==b.mode?DEXTTOP.DEXT5.setBodyValueExLikeDiv(b.value,a.ID):"setBodyValue"==b.mode?DEXTTOP.DEXT5.setBodyValue(b.value,a.ID):"setOriginalHtmlValue"==b.mode?DEXTTOP.DEXT5.setOriginalHtmlValue(b.value,
a.ID):"setHtmlContents"==b.mode&&DEXTTOP.DEXT5.setHtmlContents(b.value,a.ID):DEXTTOP.DEXT5.setHtmlContentsEw(b,a.ID),DEXTTOP.DEXT5.InitEditorDataHashTable.removeItem(a.ID)))};f.appendChild(e)}
function lightViewFunc(d,b,a){var f="",c="",e=a._FRAMEWIN.document.getElementById("dext5_lightview_"+a.ID),e=e.contentDocument?e.contentDocument:e.contentWindow.document,c=e.getElementsByTagName("head")[0].outerHTML;a._docType[a._PageProp.doctype]&&(f=a._docType[a._PageProp.doctype]);switch(d){case "setEditorMode":"edit"==b&&(f=DEXTTOP.DEXT5.config.Mode,DEXTTOP.DEXT5.config.Mode=b,DEXTTOP.G_LIGHTVIEWDOC[a.ID]=DEXTTOP.G_LIGHTVIEWDOC[a.ID].body.outerHTML,delete DEXTTOP.DEXT5.DEXTMULTIPLE["dext_frame_"+
a.ID],new DEXTTOP.Dext5editor(a.ID),DEXTTOP.DEXT5.config.Mode=f);break;case "setBodyValue":openWriteClose(e,f+"<html>"+c+("<body>"+b+"</body>")+"</html>",a);break;case "setBodyValueEx":openWriteClose(e,f+"<html>"+c+b+"</html>",a);break;case "setBodyValueExLikeDiv":var g=b.substr(0,4);d=b.substr(b.length-6,6);"<div"==g.toLowerCase()&&"</div>"==d.toLowerCase()&&(g=g.replace(g,"<body"),d=d.replace(d,"</body>"),b=b.substring(4,b.length-6),b=g+b+d);openWriteClose(e,f+"<html>"+c+b+"</html>",a);break;case "setHtmlValue":b=
getRemoveHeadScript(b);b=b.html;a._config.userCssUrl&&""!=a._config.userCssUrl&&a._config.userCssAlwaysSet&&"1"==a._config.userCssAlwaysSet&&(html=userCssSet(html,a._config.userCssUrl));openWriteClose(e,f+"<html>"+b+"</html>",a);break;case "setHtmlValueEx":b=getRemoveHeadScript(b);b=b.html;a._config.userCssUrl&&""!=a._config.userCssUrl&&a._config.userCssAlwaysSet&&"1"==a._config.userCssAlwaysSet&&(b=userCssSet(b,a._config.userCssUrl));openWriteClose(e,f+b,a);break;case "setHtmlValueExWithDocType":b=
getRemoveHeadScript(b);b=b.html;a._config.userCssUrl&&""!=a._config.userCssUrl&&a._config.userCssAlwaysSet&&"1"==a._config.userCssAlwaysSet&&(b=userCssSet(b,a._config.userCssUrl));openWriteClose(e,b,a);break;case "setOriginalHtmlValue":a._config.userCssUrl&&""!=a._config.userCssUrl&&a._config.userCssAlwaysSet&&"1"==a._config.userCssAlwaysSet&&(b=userCssSet(b,a._config.userCssUrl)),openWriteClose(e,b,a)}}
function isViewMode(d){var b=d;if(void 0==d||null==d)b=DEXTTOP.G_CURREDITOR;return"view"==b._config.mode||"lightview"==b._config.mode?!0:!1}function groupingIcon(d){}function getClientRect(d){var b={left:0,top:0,right:0,bottom:0};try{b=d.getBoundingClientRect()}catch(a){DEXTTOP&&DEXTTOP.DEXT5&&DEXTTOP.DEXT5.logMode&&console.log(a)}return b}
function set_view_mode_auto_height(d){try{setTimeout(function(){var a=DEXTTOP.G_CURREDITOR;d&&(a=d);if("1"==a._config.view_mode_auto_height||"1"==a._config.view_mode_auto_width){var b=DEXTTOP.G_LIGHTVIEWDOC[d.ID].body,c=a._DOC.documentElement,e=a._config.style.height,g=a._config.style.width,l=0;0>e.indexOf("%")&&(l=parseInt(e,10));var p=0;0>g.indexOf("%")&&(p=parseInt(g,10));var k=0,h=0,k=DEXTTOP.document.getElementById(a._config.holderID),h=getClientRect(k),m,n;void 0==h.height?m=k.offsetHeight:
m=h.height;void 0==h.width?n=k.offsetWidth:n=h.width;m=Math.round(m);n=Math.round(n);if("1"==a._config.view_mode_auto_height){e="";DEXTTOP.DEXT5.browser.mobile&&DEXTTOP.DEXT5.browser.iOS&&(e=b.style,b.style="overflow:initial !important");k=Math.max(b.scrollHeight,b.offsetHeight,c.clientHeight,c.scrollHeight,c.offsetHeight);m>k&&(k=m);DEXTTOP.DEXT5.browser.mobile&&DEXTTOP.DEXT5.browser.iOS&&(b.style=e);var q=document.body.offsetWidth<b.scrollWidth,r=document.body.offsetHeight<b.scrollHeight;if(q||
r)k+=30}else k=l,-1<e.indexOf("%")&&(k=e);if("1"==a._config.view_mode_auto_width){if(h=Math.max(b.scrollWidth,b.offsetWidth,c.clientWidth,c.scrollWidth,c.offsetWidth),q||r)h+=10}else h=p,-1<g.indexOf("%")&&(h=g);n>h&&(h=n);DEXTTOP.DEXT5.setSize(h,k,a.ID)}},250)}catch(b){DEXTTOP&&DEXTTOP.DEXT5&&DEXTTOP.DEXT5.logMode&&console.log(b)}}
function openWriteClose(d,b,a){d.open("text/html","replace");d.write(b);d.close();set_view_mode_auto_height(a);DEXTTOP.DEXT5.util.addEventEx(d,"keydown",DEXTTOP.DEXT5.LIGHTVIEWEVT._lightView_Keydown,!1);DEXTTOP.DEXT5.util.addEventEx(d,"contextmenu",DEXTTOP.DEXT5.LIGHTVIEWEVT._lightView_Contextmenu,!1);try{"function"==typeof a._config.event.setComplete?a._config.event.setComplete(a.ID):"function"==typeof DEXTTOP.dext_editor_set_complete_event&&DEXTTOP.dext_editor_set_complete_event(a.ID)}catch(f){DEXTTOP&&
DEXTTOP.DEXT5&&DEXTTOP.DEXT5.logMode&&console.log(f)}}
function getRemoveHeadScript(d){var b={html:d,scriptsAry:[]},a=d.toLowerCase().indexOf("<head"),f=d.toLowerCase().indexOf("</head>"),c=d.substring(0,a),a=d.substring(a,f+7);d=d.substring(f+7,d.length);var f=RegExp("<script[^>]*src=([\\s\\S]*?)>[\\s\\S]*?\x3c/script>","gi"),e=a.match(f);if(e){for(var g=e.length,l=0;g>l;l++)f=RegExp('<script[^>]*src="([\\s\\SS]*?)"([\\s\\S]*?)>[sS]*?\x3c/script>',"gi"),f.test(e[l]),b.scriptsAry.push(RegExp.$1);f=RegExp("<script[^>]*src=([\\s\\S]*?)>[\\s\\S]*?\x3c/script>",
"gi");a=a.replace(f,"");b.html=c+a+d}return b}function userCssSet(d,b){var a=strRetvalue=d,f='<link href="'+b+'" rel="stylesheet" type="text/css">';try{if(-1==d.indexOf(f)){var c=d.indexOf("</head>");if(-1==c){var e=d.indexOf("<body");strRetvalue=-1==e?"<head>"+f+"</head><body>"+d+"</body>":d.substring(0,e)+"<head>"+f+"</head>"+d.substring(e)}else strRetvalue=d.substring(0,c)+f+d.substring(c)}}catch(g){strRetvalue=a}return strRetvalue};
